/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.analysis;

import java.util.*;
import lParser.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    @Override
    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    @Override
    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    @Override
    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    @Override
    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    @Override
    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAProgramme(AProgramme node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAListeDeclarationVar(AListeDeclarationVar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVideListeDeclarationVar(AVideListeDeclarationVar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAListeDeclarationVarPrime(AListeDeclarationVarPrime node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVideListeDeclarationVarPrime(AVideListeDeclarationVarPrime node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADeclarationVar(ADeclarationVar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATableauDeclarationVar(ATableauDeclarationVar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAListeDeclarationFonc(AListeDeclarationFonc node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVideListeDeclarationFonc(AVideListeDeclarationFonc node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADeclarationFonc(ADeclarationFonc node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABoolType(ABoolType node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEntierType(AEntierType node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATypeTypeOptionnel(ATypeTypeOptionnel node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVideTypeOptionnel(AVideTypeOptionnel node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABlocInstruction(ABlocInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAListeInstruction(AListeInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVideListeInstruction(AVideListeInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAffectationInstruction(AAffectationInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIncrInstruction(AIncrInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASiInstruction(ASiInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASiSinonInstruction(ASiSinonInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATantQueInstruction(ATantQueInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARetourInstruction(ARetourInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAppelFonctionInstruction(AAppelFonctionInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEcrireInstruction(AEcrireInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFaireTantQueInstruction(AFaireTantQueInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVar(AVar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATableauVar(ATableauVar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAListeExp(AListeExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVideListeExp(AVideListeExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAListeExpPrime(AListeExpPrime node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVideListeExpPrime(AVideListeExpPrime node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAOuExp(AOuExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExp1Exp(AExp1Exp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEtExp1(AEtExp1 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExp2Exp1(AExp2Exp1 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEgalExp2(AEgalExp2 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInfExp2(AInfExp2 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExp3Exp2(AExp3Exp2 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPlusExp3(APlusExp3 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMoinsExp3(AMoinsExp3 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExp4Exp3(AExp4Exp3 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMultExp4(AMultExp4 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAModuloExp4(AModuloExp4 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADivExp4(ADivExp4 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExp5Exp4(AExp5Exp4 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANonExp5(ANonExp5 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExp6Exp5(AExp6Exp5 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPowerExp6(APowerExp6 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExp7Exp6(AExp7Exp6 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEntreParanthesesExp7(AEntreParanthesesExp7 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANombreExp7(ANombreExp7 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVraiExp7(AVraiExp7 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFauxExp7(AFauxExp7 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAppelFonctionExp7(AAppelFonctionExp7 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALireExp7(ALireExp7 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVariableExp7(AVariableExp7 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCrochetGauche(TCrochetGauche node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCrochetDroit(TCrochetDroit node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTParentheseGauche(TParentheseGauche node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTParentheseDroite(TParentheseDroite node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAccoladeGauche(TAccoladeGauche node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAccoladeDroite(TAccoladeDroite node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSi(TSi node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSinon(TSinon node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAlors(TAlors node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTantQue(TTantQue node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFaire(TFaire node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEcrire(TEcrire node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRetour(TRetour node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLire(TLire node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOu(TOu node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEt(TEt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEgal(TEgal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPlusegal(TPlusegal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTModulo(TModulo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTInf(TInf node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPlus(TPlus node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMoins(TMoins node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMult(TMult node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPower(TPower node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDiv(TDiv node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTExclamation(TExclamation node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBool(TBool node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEntier(TEntier node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVrai(TVrai node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFaux(TFaux node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVirgule(TVirgule node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPointVirgule(TPointVirgule node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEspace(TEspace node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCommentaire(TCommentaire node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNombre(TNombre node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIdentif(TIdentif node)
    {
        defaultCase(node);
    }

    @Override
    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    @Override
    public void caseInvalidToken(InvalidToken node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
