/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.analysis;

import java.util.*;
import lParser.node.*;

public class DepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getPProgramme().apply(this);
        node.getEOF().apply(this);
        outStart(node);
    }

    public void inAProgramme(AProgramme node)
    {
        defaultIn(node);
    }

    public void outAProgramme(AProgramme node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAProgramme(AProgramme node)
    {
        inAProgramme(node);
        if(node.getListedecvar() != null)
        {
            node.getListedecvar().apply(this);
        }
        if(node.getListedecfonc() != null)
        {
            node.getListedecfonc().apply(this);
        }
        outAProgramme(node);
    }

    public void inADecvarListedecvar(ADecvarListedecvar node)
    {
        defaultIn(node);
    }

    public void outADecvarListedecvar(ADecvarListedecvar node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecvarListedecvar(ADecvarListedecvar node)
    {
        inADecvarListedecvar(node);
        if(node.getDecvar() != null)
        {
            node.getDecvar().apply(this);
        }
        if(node.getListedecvar1() != null)
        {
            node.getListedecvar1().apply(this);
        }
        outADecvarListedecvar(node);
    }

    public void inAVideListedecvar(AVideListedecvar node)
    {
        defaultIn(node);
    }

    public void outAVideListedecvar(AVideListedecvar node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVideListedecvar(AVideListedecvar node)
    {
        inAVideListedecvar(node);
        outAVideListedecvar(node);
    }

    public void inARestedecvarListedecvar1(ARestedecvarListedecvar1 node)
    {
        defaultIn(node);
    }

    public void outARestedecvarListedecvar1(ARestedecvarListedecvar1 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARestedecvarListedecvar1(ARestedecvarListedecvar1 node)
    {
        inARestedecvarListedecvar1(node);
        if(node.getVirgule() != null)
        {
            node.getVirgule().apply(this);
        }
        if(node.getDecvar() != null)
        {
            node.getDecvar().apply(this);
        }
        if(node.getListedecvar1() != null)
        {
            node.getListedecvar1().apply(this);
        }
        outARestedecvarListedecvar1(node);
    }

    public void inAVideListedecvar1(AVideListedecvar1 node)
    {
        defaultIn(node);
    }

    public void outAVideListedecvar1(AVideListedecvar1 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVideListedecvar1(AVideListedecvar1 node)
    {
        inAVideListedecvar1(node);
        outAVideListedecvar1(node);
    }

    public void inAVarsimpleDecvar(AVarsimpleDecvar node)
    {
        defaultIn(node);
    }

    public void outAVarsimpleDecvar(AVarsimpleDecvar node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVarsimpleDecvar(AVarsimpleDecvar node)
    {
        inAVarsimpleDecvar(node);
        if(node.getPremier() != null)
        {
            node.getPremier().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAVarsimpleDecvar(node);
    }

    public void inAVartabDecvar(AVartabDecvar node)
    {
        defaultIn(node);
    }

    public void outAVartabDecvar(AVartabDecvar node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVartabDecvar(AVartabDecvar node)
    {
        inAVartabDecvar(node);
        if(node.getSecond() != null)
        {
            node.getSecond().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getCroG() != null)
        {
            node.getCroG().apply(this);
        }
        if(node.getNombre() != null)
        {
            node.getNombre().apply(this);
        }
        if(node.getCroD() != null)
        {
            node.getCroD().apply(this);
        }
        outAVartabDecvar(node);
    }

    public void inAEntierType(AEntierType node)
    {
        defaultIn(node);
    }

    public void outAEntierType(AEntierType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEntierType(AEntierType node)
    {
        inAEntierType(node);
        if(node.getEntier() != null)
        {
            node.getEntier().apply(this);
        }
        outAEntierType(node);
    }

    public void inABooleanType(ABooleanType node)
    {
        defaultIn(node);
    }

    public void outABooleanType(ABooleanType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABooleanType(ABooleanType node)
    {
        inABooleanType(node);
        if(node.getBool() != null)
        {
            node.getBool().apply(this);
        }
        outABooleanType(node);
    }

    public void inADecfonctionListedecfonc(ADecfonctionListedecfonc node)
    {
        defaultIn(node);
    }

    public void outADecfonctionListedecfonc(ADecfonctionListedecfonc node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecfonctionListedecfonc(ADecfonctionListedecfonc node)
    {
        inADecfonctionListedecfonc(node);
        if(node.getFonction() != null)
        {
            node.getFonction().apply(this);
        }
        if(node.getListedecfonc() != null)
        {
            node.getListedecfonc().apply(this);
        }
        outADecfonctionListedecfonc(node);
    }

    public void inAVideListedecfonc(AVideListedecfonc node)
    {
        defaultIn(node);
    }

    public void outAVideListedecfonc(AVideListedecfonc node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVideListedecfonc(AVideListedecfonc node)
    {
        inAVideListedecfonc(node);
        outAVideListedecfonc(node);
    }

    public void inAFonction(AFonction node)
    {
        defaultIn(node);
    }

    public void outAFonction(AFonction node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFonction(AFonction node)
    {
        inAFonction(node);
        if(node.getTypeoptionnel() != null)
        {
            node.getTypeoptionnel().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getParG() != null)
        {
            node.getParG().apply(this);
        }
        if(node.getPremier() != null)
        {
            node.getPremier().apply(this);
        }
        if(node.getParD() != null)
        {
            node.getParD().apply(this);
        }
        if(node.getSecond() != null)
        {
            node.getSecond().apply(this);
        }
        if(node.getBlocinstructions() != null)
        {
            node.getBlocinstructions().apply(this);
        }
        outAFonction(node);
    }

    public void inATypevarTypeoptionnel(ATypevarTypeoptionnel node)
    {
        defaultIn(node);
    }

    public void outATypevarTypeoptionnel(ATypevarTypeoptionnel node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATypevarTypeoptionnel(ATypevarTypeoptionnel node)
    {
        inATypevarTypeoptionnel(node);
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        outATypevarTypeoptionnel(node);
    }

    public void inAVideTypeoptionnel(AVideTypeoptionnel node)
    {
        defaultIn(node);
    }

    public void outAVideTypeoptionnel(AVideTypeoptionnel node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVideTypeoptionnel(AVideTypeoptionnel node)
    {
        inAVideTypeoptionnel(node);
        outAVideTypeoptionnel(node);
    }

    public void inABlocBlocinstructions(ABlocBlocinstructions node)
    {
        defaultIn(node);
    }

    public void outABlocBlocinstructions(ABlocBlocinstructions node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlocBlocinstructions(ABlocBlocinstructions node)
    {
        inABlocBlocinstructions(node);
        if(node.getAccG() != null)
        {
            node.getAccG().apply(this);
        }
        if(node.getListeinstructions() != null)
        {
            node.getListeinstructions().apply(this);
        }
        if(node.getAccD() != null)
        {
            node.getAccD().apply(this);
        }
        outABlocBlocinstructions(node);
    }

    public void inAInstructionsListeinstructions(AInstructionsListeinstructions node)
    {
        defaultIn(node);
    }

    public void outAInstructionsListeinstructions(AInstructionsListeinstructions node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAInstructionsListeinstructions(AInstructionsListeinstructions node)
    {
        inAInstructionsListeinstructions(node);
        if(node.getInstruction() != null)
        {
            node.getInstruction().apply(this);
        }
        if(node.getListeinstructions() != null)
        {
            node.getListeinstructions().apply(this);
        }
        outAInstructionsListeinstructions(node);
    }

    public void inAVideListeinstructions(AVideListeinstructions node)
    {
        defaultIn(node);
    }

    public void outAVideListeinstructions(AVideListeinstructions node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVideListeinstructions(AVideListeinstructions node)
    {
        inAVideListeinstructions(node);
        outAVideListeinstructions(node);
    }

    public void inAAffectationInstruction(AAffectationInstruction node)
    {
        defaultIn(node);
    }

    public void outAAffectationInstruction(AAffectationInstruction node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAffectationInstruction(AAffectationInstruction node)
    {
        inAAffectationInstruction(node);
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        if(node.getEgal() != null)
        {
            node.getEgal().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        if(node.getPVirgule() != null)
        {
            node.getPVirgule().apply(this);
        }
        outAAffectationInstruction(node);
    }

    public void inATantqueInstruction(ATantqueInstruction node)
    {
        defaultIn(node);
    }

    public void outATantqueInstruction(ATantqueInstruction node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATantqueInstruction(ATantqueInstruction node)
    {
        inATantqueInstruction(node);
        if(node.getTq() != null)
        {
            node.getTq().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        if(node.getFaire() != null)
        {
            node.getFaire().apply(this);
        }
        if(node.getBlocinstructions() != null)
        {
            node.getBlocinstructions().apply(this);
        }
        outATantqueInstruction(node);
    }

    public void inASialorsInstruction(ASialorsInstruction node)
    {
        defaultIn(node);
    }

    public void outASialorsInstruction(ASialorsInstruction node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASialorsInstruction(ASialorsInstruction node)
    {
        inASialorsInstruction(node);
        if(node.getSi() != null)
        {
            node.getSi().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        if(node.getAlors() != null)
        {
            node.getAlors().apply(this);
        }
        if(node.getBlocinstructions() != null)
        {
            node.getBlocinstructions().apply(this);
        }
        outASialorsInstruction(node);
    }

    public void inASisinonInstruction(ASisinonInstruction node)
    {
        defaultIn(node);
    }

    public void outASisinonInstruction(ASisinonInstruction node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASisinonInstruction(ASisinonInstruction node)
    {
        inASisinonInstruction(node);
        if(node.getSi() != null)
        {
            node.getSi().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        if(node.getAlors() != null)
        {
            node.getAlors().apply(this);
        }
        if(node.getPremier() != null)
        {
            node.getPremier().apply(this);
        }
        if(node.getSinon() != null)
        {
            node.getSinon().apply(this);
        }
        if(node.getSecond() != null)
        {
            node.getSecond().apply(this);
        }
        outASisinonInstruction(node);
    }

    public void inARetourInstruction(ARetourInstruction node)
    {
        defaultIn(node);
    }

    public void outARetourInstruction(ARetourInstruction node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARetourInstruction(ARetourInstruction node)
    {
        inARetourInstruction(node);
        if(node.getRetour() != null)
        {
            node.getRetour().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        if(node.getPVirgule() != null)
        {
            node.getPVirgule().apply(this);
        }
        outARetourInstruction(node);
    }

    public void inAEcrireInstruction(AEcrireInstruction node)
    {
        defaultIn(node);
    }

    public void outAEcrireInstruction(AEcrireInstruction node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEcrireInstruction(AEcrireInstruction node)
    {
        inAEcrireInstruction(node);
        if(node.getEcrire() != null)
        {
            node.getEcrire().apply(this);
        }
        if(node.getParG() != null)
        {
            node.getParG().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        if(node.getParD() != null)
        {
            node.getParD().apply(this);
        }
        if(node.getPVirgule() != null)
        {
            node.getPVirgule().apply(this);
        }
        outAEcrireInstruction(node);
    }

    public void inAIdInstruction(AIdInstruction node)
    {
        defaultIn(node);
    }

    public void outAIdInstruction(AIdInstruction node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdInstruction(AIdInstruction node)
    {
        inAIdInstruction(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getParG() != null)
        {
            node.getParG().apply(this);
        }
        if(node.getListeexpressions() != null)
        {
            node.getListeexpressions().apply(this);
        }
        if(node.getParD() != null)
        {
            node.getParD().apply(this);
        }
        if(node.getPVirgule() != null)
        {
            node.getPVirgule().apply(this);
        }
        outAIdInstruction(node);
    }

    public void inAIdentificateurVar(AIdentificateurVar node)
    {
        defaultIn(node);
    }

    public void outAIdentificateurVar(AIdentificateurVar node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdentificateurVar(AIdentificateurVar node)
    {
        inAIdentificateurVar(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAIdentificateurVar(node);
    }

    public void inACasetableauVar(ACasetableauVar node)
    {
        defaultIn(node);
    }

    public void outACasetableauVar(ACasetableauVar node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACasetableauVar(ACasetableauVar node)
    {
        inACasetableauVar(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getCroG() != null)
        {
            node.getCroG().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        if(node.getCroD() != null)
        {
            node.getCroD().apply(this);
        }
        outACasetableauVar(node);
    }

    public void inAListeparametresListeexpressions(AListeparametresListeexpressions node)
    {
        defaultIn(node);
    }

    public void outAListeparametresListeexpressions(AListeparametresListeexpressions node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListeparametresListeexpressions(AListeparametresListeexpressions node)
    {
        inAListeparametresListeexpressions(node);
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        if(node.getListeexpressions1() != null)
        {
            node.getListeexpressions1().apply(this);
        }
        outAListeparametresListeexpressions(node);
    }

    public void inAVideListeexpressions(AVideListeexpressions node)
    {
        defaultIn(node);
    }

    public void outAVideListeexpressions(AVideListeexpressions node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVideListeexpressions(AVideListeexpressions node)
    {
        inAVideListeexpressions(node);
        outAVideListeexpressions(node);
    }

    public void inAResteparametrescommencantvirguleListeexpressions1(AResteparametrescommencantvirguleListeexpressions1 node)
    {
        defaultIn(node);
    }

    public void outAResteparametrescommencantvirguleListeexpressions1(AResteparametrescommencantvirguleListeexpressions1 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAResteparametrescommencantvirguleListeexpressions1(AResteparametrescommencantvirguleListeexpressions1 node)
    {
        inAResteparametrescommencantvirguleListeexpressions1(node);
        if(node.getVirgule() != null)
        {
            node.getVirgule().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        if(node.getListeexpressions1() != null)
        {
            node.getListeexpressions1().apply(this);
        }
        outAResteparametrescommencantvirguleListeexpressions1(node);
    }

    public void inAVideListeexpressions1(AVideListeexpressions1 node)
    {
        defaultIn(node);
    }

    public void outAVideListeexpressions1(AVideListeexpressions1 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVideListeexpressions1(AVideListeexpressions1 node)
    {
        inAVideListeexpressions1(node);
        outAVideListeexpressions1(node);
    }

    public void inAOuExpression(AOuExpression node)
    {
        defaultIn(node);
    }

    public void outAOuExpression(AOuExpression node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOuExpression(AOuExpression node)
    {
        inAOuExpression(node);
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        if(node.getOu() != null)
        {
            node.getOu().apply(this);
        }
        if(node.getExp1() != null)
        {
            node.getExp1().apply(this);
        }
        outAOuExpression(node);
    }

    public void inAExp1Expression(AExp1Expression node)
    {
        defaultIn(node);
    }

    public void outAExp1Expression(AExp1Expression node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExp1Expression(AExp1Expression node)
    {
        inAExp1Expression(node);
        if(node.getExp1() != null)
        {
            node.getExp1().apply(this);
        }
        outAExp1Expression(node);
    }

    public void inAEtExp1(AEtExp1 node)
    {
        defaultIn(node);
    }

    public void outAEtExp1(AEtExp1 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEtExp1(AEtExp1 node)
    {
        inAEtExp1(node);
        if(node.getExp1() != null)
        {
            node.getExp1().apply(this);
        }
        if(node.getEt() != null)
        {
            node.getEt().apply(this);
        }
        if(node.getExp2() != null)
        {
            node.getExp2().apply(this);
        }
        outAEtExp1(node);
    }

    public void inAExp2Exp1(AExp2Exp1 node)
    {
        defaultIn(node);
    }

    public void outAExp2Exp1(AExp2Exp1 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExp2Exp1(AExp2Exp1 node)
    {
        inAExp2Exp1(node);
        if(node.getExp2() != null)
        {
            node.getExp2().apply(this);
        }
        outAExp2Exp1(node);
    }

    public void inAEgalExp2(AEgalExp2 node)
    {
        defaultIn(node);
    }

    public void outAEgalExp2(AEgalExp2 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEgalExp2(AEgalExp2 node)
    {
        inAEgalExp2(node);
        if(node.getExp2() != null)
        {
            node.getExp2().apply(this);
        }
        if(node.getEgal() != null)
        {
            node.getEgal().apply(this);
        }
        if(node.getExp3() != null)
        {
            node.getExp3().apply(this);
        }
        outAEgalExp2(node);
    }

    public void inAInfExp2(AInfExp2 node)
    {
        defaultIn(node);
    }

    public void outAInfExp2(AInfExp2 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAInfExp2(AInfExp2 node)
    {
        inAInfExp2(node);
        if(node.getExp2() != null)
        {
            node.getExp2().apply(this);
        }
        if(node.getInf() != null)
        {
            node.getInf().apply(this);
        }
        if(node.getExp3() != null)
        {
            node.getExp3().apply(this);
        }
        outAInfExp2(node);
    }

    public void inAExp3Exp2(AExp3Exp2 node)
    {
        defaultIn(node);
    }

    public void outAExp3Exp2(AExp3Exp2 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExp3Exp2(AExp3Exp2 node)
    {
        inAExp3Exp2(node);
        if(node.getExp3() != null)
        {
            node.getExp3().apply(this);
        }
        outAExp3Exp2(node);
    }

    public void inAPlusExp3(APlusExp3 node)
    {
        defaultIn(node);
    }

    public void outAPlusExp3(APlusExp3 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPlusExp3(APlusExp3 node)
    {
        inAPlusExp3(node);
        if(node.getExp3() != null)
        {
            node.getExp3().apply(this);
        }
        if(node.getPlus() != null)
        {
            node.getPlus().apply(this);
        }
        if(node.getExp4() != null)
        {
            node.getExp4().apply(this);
        }
        outAPlusExp3(node);
    }

    public void inAMoinsExp3(AMoinsExp3 node)
    {
        defaultIn(node);
    }

    public void outAMoinsExp3(AMoinsExp3 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMoinsExp3(AMoinsExp3 node)
    {
        inAMoinsExp3(node);
        if(node.getExp3() != null)
        {
            node.getExp3().apply(this);
        }
        if(node.getMoins() != null)
        {
            node.getMoins().apply(this);
        }
        if(node.getExp4() != null)
        {
            node.getExp4().apply(this);
        }
        outAMoinsExp3(node);
    }

    public void inAExp5Exp3(AExp5Exp3 node)
    {
        defaultIn(node);
    }

    public void outAExp5Exp3(AExp5Exp3 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExp5Exp3(AExp5Exp3 node)
    {
        inAExp5Exp3(node);
        if(node.getExp4() != null)
        {
            node.getExp4().apply(this);
        }
        outAExp5Exp3(node);
    }

    public void inAMultExp4(AMultExp4 node)
    {
        defaultIn(node);
    }

    public void outAMultExp4(AMultExp4 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultExp4(AMultExp4 node)
    {
        inAMultExp4(node);
        if(node.getExp4() != null)
        {
            node.getExp4().apply(this);
        }
        if(node.getMult() != null)
        {
            node.getMult().apply(this);
        }
        if(node.getExp5() != null)
        {
            node.getExp5().apply(this);
        }
        outAMultExp4(node);
    }

    public void inADivExp4(ADivExp4 node)
    {
        defaultIn(node);
    }

    public void outADivExp4(ADivExp4 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADivExp4(ADivExp4 node)
    {
        inADivExp4(node);
        if(node.getExp4() != null)
        {
            node.getExp4().apply(this);
        }
        if(node.getDiv() != null)
        {
            node.getDiv().apply(this);
        }
        if(node.getExp5() != null)
        {
            node.getExp5().apply(this);
        }
        outADivExp4(node);
    }

    public void inAExp5Exp4(AExp5Exp4 node)
    {
        defaultIn(node);
    }

    public void outAExp5Exp4(AExp5Exp4 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExp5Exp4(AExp5Exp4 node)
    {
        inAExp5Exp4(node);
        if(node.getExp5() != null)
        {
            node.getExp5().apply(this);
        }
        outAExp5Exp4(node);
    }

    public void inANonExp5(ANonExp5 node)
    {
        defaultIn(node);
    }

    public void outANonExp5(ANonExp5 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANonExp5(ANonExp5 node)
    {
        inANonExp5(node);
        if(node.getNon() != null)
        {
            node.getNon().apply(this);
        }
        if(node.getExp5() != null)
        {
            node.getExp5().apply(this);
        }
        outANonExp5(node);
    }

    public void inAExp6Exp5(AExp6Exp5 node)
    {
        defaultIn(node);
    }

    public void outAExp6Exp5(AExp6Exp5 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExp6Exp5(AExp6Exp5 node)
    {
        inAExp6Exp5(node);
        if(node.getExp6() != null)
        {
            node.getExp6().apply(this);
        }
        outAExp6Exp5(node);
    }

    public void inAParenthesesExp6(AParenthesesExp6 node)
    {
        defaultIn(node);
    }

    public void outAParenthesesExp6(AParenthesesExp6 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParenthesesExp6(AParenthesesExp6 node)
    {
        inAParenthesesExp6(node);
        if(node.getParG() != null)
        {
            node.getParG().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        if(node.getParD() != null)
        {
            node.getParD().apply(this);
        }
        outAParenthesesExp6(node);
    }

    public void inAVarExp6(AVarExp6 node)
    {
        defaultIn(node);
    }

    public void outAVarExp6(AVarExp6 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVarExp6(AVarExp6 node)
    {
        inAVarExp6(node);
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        outAVarExp6(node);
    }

    public void inANombreExp6(ANombreExp6 node)
    {
        defaultIn(node);
    }

    public void outANombreExp6(ANombreExp6 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANombreExp6(ANombreExp6 node)
    {
        inANombreExp6(node);
        if(node.getNombre() != null)
        {
            node.getNombre().apply(this);
        }
        outANombreExp6(node);
    }

    public void inAAppelfonction2Exp6(AAppelfonction2Exp6 node)
    {
        defaultIn(node);
    }

    public void outAAppelfonction2Exp6(AAppelfonction2Exp6 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAppelfonction2Exp6(AAppelfonction2Exp6 node)
    {
        inAAppelfonction2Exp6(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getParG() != null)
        {
            node.getParG().apply(this);
        }
        if(node.getListeexpressions() != null)
        {
            node.getListeexpressions().apply(this);
        }
        if(node.getParD() != null)
        {
            node.getParD().apply(this);
        }
        outAAppelfonction2Exp6(node);
    }

    public void inALireExp6(ALireExp6 node)
    {
        defaultIn(node);
    }

    public void outALireExp6(ALireExp6 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALireExp6(ALireExp6 node)
    {
        inALireExp6(node);
        if(node.getLire() != null)
        {
            node.getLire().apply(this);
        }
        if(node.getParG() != null)
        {
            node.getParG().apply(this);
        }
        if(node.getParD() != null)
        {
            node.getParD().apply(this);
        }
        outALireExp6(node);
    }

    public void inAVraiExp6(AVraiExp6 node)
    {
        defaultIn(node);
    }

    public void outAVraiExp6(AVraiExp6 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVraiExp6(AVraiExp6 node)
    {
        inAVraiExp6(node);
        if(node.getVrai() != null)
        {
            node.getVrai().apply(this);
        }
        outAVraiExp6(node);
    }

    public void inAFauxExp6(AFauxExp6 node)
    {
        defaultIn(node);
    }

    public void outAFauxExp6(AFauxExp6 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFauxExp6(AFauxExp6 node)
    {
        inAFauxExp6(node);
        if(node.getFaux() != null)
        {
            node.getFaux().apply(this);
        }
        outAFauxExp6(node);
    }
}
