/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.node;

import lParser.analysis.*;

@SuppressWarnings("nls")
public final class ALireExp6 extends PExp6
{
    private TLire _lire_;
    private TParG _parG_;
    private TParD _parD_;

    public ALireExp6()
    {
        // Constructor
    }

    public ALireExp6(
        @SuppressWarnings("hiding") TLire _lire_,
        @SuppressWarnings("hiding") TParG _parG_,
        @SuppressWarnings("hiding") TParD _parD_)
    {
        // Constructor
        setLire(_lire_);

        setParG(_parG_);

        setParD(_parD_);

    }

    @Override
    public Object clone()
    {
        return new ALireExp6(
            cloneNode(this._lire_),
            cloneNode(this._parG_),
            cloneNode(this._parD_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALireExp6(this);
    }

    public TLire getLire()
    {
        return this._lire_;
    }

    public void setLire(TLire node)
    {
        if(this._lire_ != null)
        {
            this._lire_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lire_ = node;
    }

    public TParG getParG()
    {
        return this._parG_;
    }

    public void setParG(TParG node)
    {
        if(this._parG_ != null)
        {
            this._parG_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parG_ = node;
    }

    public TParD getParD()
    {
        return this._parD_;
    }

    public void setParD(TParD node)
    {
        if(this._parD_ != null)
        {
            this._parD_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parD_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lire_)
            + toString(this._parG_)
            + toString(this._parD_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lire_ == child)
        {
            this._lire_ = null;
            return;
        }

        if(this._parG_ == child)
        {
            this._parG_ = null;
            return;
        }

        if(this._parD_ == child)
        {
            this._parD_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lire_ == oldChild)
        {
            setLire((TLire) newChild);
            return;
        }

        if(this._parG_ == oldChild)
        {
            setParG((TParG) newChild);
            return;
        }

        if(this._parD_ == oldChild)
        {
            setParD((TParD) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
