/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.node;

import lParser.analysis.*;

@SuppressWarnings("nls")
public final class AListeparametresListeexpressions extends PListeexpressions
{
    private PExpression _expression_;
    private PListeexpressions1 _listeexpressions1_;

    public AListeparametresListeexpressions()
    {
        // Constructor
    }

    public AListeparametresListeexpressions(
        @SuppressWarnings("hiding") PExpression _expression_,
        @SuppressWarnings("hiding") PListeexpressions1 _listeexpressions1_)
    {
        // Constructor
        setExpression(_expression_);

        setListeexpressions1(_listeexpressions1_);

    }

    @Override
    public Object clone()
    {
        return new AListeparametresListeexpressions(
            cloneNode(this._expression_),
            cloneNode(this._listeexpressions1_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListeparametresListeexpressions(this);
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    public PListeexpressions1 getListeexpressions1()
    {
        return this._listeexpressions1_;
    }

    public void setListeexpressions1(PListeexpressions1 node)
    {
        if(this._listeexpressions1_ != null)
        {
            this._listeexpressions1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listeexpressions1_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expression_)
            + toString(this._listeexpressions1_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        if(this._listeexpressions1_ == child)
        {
            this._listeexpressions1_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        if(this._listeexpressions1_ == oldChild)
        {
            setListeexpressions1((PListeexpressions1) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
