/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.node;

import lParser.analysis.*;

@SuppressWarnings("nls")
public final class APowerExp6 extends PExp6
{
    private PExp6 _exp6_;
    private TPower _power_;

    public APowerExp6()
    {
        // Constructor
    }

    public APowerExp6(
        @SuppressWarnings("hiding") PExp6 _exp6_,
        @SuppressWarnings("hiding") TPower _power_)
    {
        // Constructor
        setExp6(_exp6_);

        setPower(_power_);

    }

    @Override
    public Object clone()
    {
        return new APowerExp6(
            cloneNode(this._exp6_),
            cloneNode(this._power_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPowerExp6(this);
    }

    public PExp6 getExp6()
    {
        return this._exp6_;
    }

    public void setExp6(PExp6 node)
    {
        if(this._exp6_ != null)
        {
            this._exp6_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp6_ = node;
    }

    public TPower getPower()
    {
        return this._power_;
    }

    public void setPower(TPower node)
    {
        if(this._power_ != null)
        {
            this._power_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._power_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp6_)
            + toString(this._power_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp6_ == child)
        {
            this._exp6_ = null;
            return;
        }

        if(this._power_ == child)
        {
            this._power_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp6_ == oldChild)
        {
            setExp6((PExp6) newChild);
            return;
        }

        if(this._power_ == oldChild)
        {
            setPower((TPower) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
