/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.node;

import lParser.analysis.*;

@SuppressWarnings("nls")
public final class TPlusegal extends Token
{
    public TPlusegal()
    {
        super.setText("+=");
    }

    public TPlusegal(int line, int pos)
    {
        super.setText("+=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPlusegal(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPlusegal(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPlusegal text.");
    }
}
