/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.node;

import lParser.analysis.*;

@SuppressWarnings("nls")
public final class AFaireTantQueInstruction extends PInstruction
{
    private TFaire _faire_;
    private PBlocInstruction _blocInstruction_;
    private TTantQue _tantQue_;
    private PExp _exp_;

    public AFaireTantQueInstruction()
    {
        // Constructor
    }

    public AFaireTantQueInstruction(
        @SuppressWarnings("hiding") TFaire _faire_,
        @SuppressWarnings("hiding") PBlocInstruction _blocInstruction_,
        @SuppressWarnings("hiding") TTantQue _tantQue_,
        @SuppressWarnings("hiding") PExp _exp_)
    {
        // Constructor
        setFaire(_faire_);

        setBlocInstruction(_blocInstruction_);

        setTantQue(_tantQue_);

        setExp(_exp_);

    }

    @Override
    public Object clone()
    {
        return new AFaireTantQueInstruction(
            cloneNode(this._faire_),
            cloneNode(this._blocInstruction_),
            cloneNode(this._tantQue_),
            cloneNode(this._exp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFaireTantQueInstruction(this);
    }

    public TFaire getFaire()
    {
        return this._faire_;
    }

    public void setFaire(TFaire node)
    {
        if(this._faire_ != null)
        {
            this._faire_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._faire_ = node;
    }

    public PBlocInstruction getBlocInstruction()
    {
        return this._blocInstruction_;
    }

    public void setBlocInstruction(PBlocInstruction node)
    {
        if(this._blocInstruction_ != null)
        {
            this._blocInstruction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._blocInstruction_ = node;
    }

    public TTantQue getTantQue()
    {
        return this._tantQue_;
    }

    public void setTantQue(TTantQue node)
    {
        if(this._tantQue_ != null)
        {
            this._tantQue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tantQue_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._faire_)
            + toString(this._blocInstruction_)
            + toString(this._tantQue_)
            + toString(this._exp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._faire_ == child)
        {
            this._faire_ = null;
            return;
        }

        if(this._blocInstruction_ == child)
        {
            this._blocInstruction_ = null;
            return;
        }

        if(this._tantQue_ == child)
        {
            this._tantQue_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._faire_ == oldChild)
        {
            setFaire((TFaire) newChild);
            return;
        }

        if(this._blocInstruction_ == oldChild)
        {
            setBlocInstruction((PBlocInstruction) newChild);
            return;
        }

        if(this._tantQue_ == oldChild)
        {
            setTantQue((TTantQue) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
