/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.node;

import lParser.analysis.*;

@SuppressWarnings("nls")
public final class AListeDeclarationFonc extends PListeDeclarationFonc
{
    private PDeclarationFonc _declarationFonc_;
    private PListeDeclarationFonc _listeDeclarationFonc_;

    public AListeDeclarationFonc()
    {
        // Constructor
    }

    public AListeDeclarationFonc(
        @SuppressWarnings("hiding") PDeclarationFonc _declarationFonc_,
        @SuppressWarnings("hiding") PListeDeclarationFonc _listeDeclarationFonc_)
    {
        // Constructor
        setDeclarationFonc(_declarationFonc_);

        setListeDeclarationFonc(_listeDeclarationFonc_);

    }

    @Override
    public Object clone()
    {
        return new AListeDeclarationFonc(
            cloneNode(this._declarationFonc_),
            cloneNode(this._listeDeclarationFonc_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListeDeclarationFonc(this);
    }

    public PDeclarationFonc getDeclarationFonc()
    {
        return this._declarationFonc_;
    }

    public void setDeclarationFonc(PDeclarationFonc node)
    {
        if(this._declarationFonc_ != null)
        {
            this._declarationFonc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declarationFonc_ = node;
    }

    public PListeDeclarationFonc getListeDeclarationFonc()
    {
        return this._listeDeclarationFonc_;
    }

    public void setListeDeclarationFonc(PListeDeclarationFonc node)
    {
        if(this._listeDeclarationFonc_ != null)
        {
            this._listeDeclarationFonc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listeDeclarationFonc_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declarationFonc_)
            + toString(this._listeDeclarationFonc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declarationFonc_ == child)
        {
            this._declarationFonc_ = null;
            return;
        }

        if(this._listeDeclarationFonc_ == child)
        {
            this._listeDeclarationFonc_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._declarationFonc_ == oldChild)
        {
            setDeclarationFonc((PDeclarationFonc) newChild);
            return;
        }

        if(this._listeDeclarationFonc_ == oldChild)
        {
            setListeDeclarationFonc((PListeDeclarationFonc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
