/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.node;

import lParser.analysis.*;

@SuppressWarnings("nls")
public final class AProgramme extends PProgramme
{
    private PListeDeclarationVar _listeDeclarationVar_;
    private PListeDeclarationFonc _listeDeclarationFonc_;

    public AProgramme()
    {
        // Constructor
    }

    public AProgramme(
        @SuppressWarnings("hiding") PListeDeclarationVar _listeDeclarationVar_,
        @SuppressWarnings("hiding") PListeDeclarationFonc _listeDeclarationFonc_)
    {
        // Constructor
        setListeDeclarationVar(_listeDeclarationVar_);

        setListeDeclarationFonc(_listeDeclarationFonc_);

    }

    @Override
    public Object clone()
    {
        return new AProgramme(
            cloneNode(this._listeDeclarationVar_),
            cloneNode(this._listeDeclarationFonc_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProgramme(this);
    }

    public PListeDeclarationVar getListeDeclarationVar()
    {
        return this._listeDeclarationVar_;
    }

    public void setListeDeclarationVar(PListeDeclarationVar node)
    {
        if(this._listeDeclarationVar_ != null)
        {
            this._listeDeclarationVar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listeDeclarationVar_ = node;
    }

    public PListeDeclarationFonc getListeDeclarationFonc()
    {
        return this._listeDeclarationFonc_;
    }

    public void setListeDeclarationFonc(PListeDeclarationFonc node)
    {
        if(this._listeDeclarationFonc_ != null)
        {
            this._listeDeclarationFonc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listeDeclarationFonc_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._listeDeclarationVar_)
            + toString(this._listeDeclarationFonc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._listeDeclarationVar_ == child)
        {
            this._listeDeclarationVar_ = null;
            return;
        }

        if(this._listeDeclarationFonc_ == child)
        {
            this._listeDeclarationFonc_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._listeDeclarationVar_ == oldChild)
        {
            setListeDeclarationVar((PListeDeclarationVar) newChild);
            return;
        }

        if(this._listeDeclarationFonc_ == oldChild)
        {
            setListeDeclarationFonc((PListeDeclarationFonc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
