/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.node;

import lParser.analysis.*;

@SuppressWarnings("nls")
public final class AVartabDecvar extends PDecvar
{
    private PType _second_;
    private TId _id_;
    private TCroG _croG_;
    private TNombre _nombre_;
    private TCroD _croD_;

    public AVartabDecvar()
    {
        // Constructor
    }

    public AVartabDecvar(
        @SuppressWarnings("hiding") PType _second_,
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TCroG _croG_,
        @SuppressWarnings("hiding") TNombre _nombre_,
        @SuppressWarnings("hiding") TCroD _croD_)
    {
        // Constructor
        setSecond(_second_);

        setId(_id_);

        setCroG(_croG_);

        setNombre(_nombre_);

        setCroD(_croD_);

    }

    @Override
    public Object clone()
    {
        return new AVartabDecvar(
            cloneNode(this._second_),
            cloneNode(this._id_),
            cloneNode(this._croG_),
            cloneNode(this._nombre_),
            cloneNode(this._croD_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVartabDecvar(this);
    }

    public PType getSecond()
    {
        return this._second_;
    }

    public void setSecond(PType node)
    {
        if(this._second_ != null)
        {
            this._second_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._second_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TCroG getCroG()
    {
        return this._croG_;
    }

    public void setCroG(TCroG node)
    {
        if(this._croG_ != null)
        {
            this._croG_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._croG_ = node;
    }

    public TNombre getNombre()
    {
        return this._nombre_;
    }

    public void setNombre(TNombre node)
    {
        if(this._nombre_ != null)
        {
            this._nombre_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nombre_ = node;
    }

    public TCroD getCroD()
    {
        return this._croD_;
    }

    public void setCroD(TCroD node)
    {
        if(this._croD_ != null)
        {
            this._croD_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._croD_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._second_)
            + toString(this._id_)
            + toString(this._croG_)
            + toString(this._nombre_)
            + toString(this._croD_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._second_ == child)
        {
            this._second_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._croG_ == child)
        {
            this._croG_ = null;
            return;
        }

        if(this._nombre_ == child)
        {
            this._nombre_ = null;
            return;
        }

        if(this._croD_ == child)
        {
            this._croD_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._second_ == oldChild)
        {
            setSecond((PType) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._croG_ == oldChild)
        {
            setCroG((TCroG) newChild);
            return;
        }

        if(this._nombre_ == oldChild)
        {
            setNombre((TNombre) newChild);
            return;
        }

        if(this._croD_ == oldChild)
        {
            setCroD((TCroD) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
