/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.node;

import lParser.analysis.*;

@SuppressWarnings("nls")
public final class AVarsimpleDecvar extends PDecvar
{
    private PType _premier_;
    private TId _id_;

    public AVarsimpleDecvar()
    {
        // Constructor
    }

    public AVarsimpleDecvar(
        @SuppressWarnings("hiding") PType _premier_,
        @SuppressWarnings("hiding") TId _id_)
    {
        // Constructor
        setPremier(_premier_);

        setId(_id_);

    }

    @Override
    public Object clone()
    {
        return new AVarsimpleDecvar(
            cloneNode(this._premier_),
            cloneNode(this._id_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarsimpleDecvar(this);
    }

    public PType getPremier()
    {
        return this._premier_;
    }

    public void setPremier(PType node)
    {
        if(this._premier_ != null)
        {
            this._premier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._premier_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._premier_)
            + toString(this._id_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._premier_ == child)
        {
            this._premier_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._premier_ == oldChild)
        {
            setPremier((PType) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
