<Start>
 <AProgramme>
  <AListeDeclarationVar>
   <ATableauDeclarationVar>
    <AEntierType>
    </AEntierType>
   </ATableauDeclarationVar>
   <AVideListeDeclarationVarPrime>
   </AVideListeDeclarationVarPrime>
  </AListeDeclarationVar>
  <AListeDeclarationFonc>
   <ADeclarationFonc>
    <AVideTypeOptionnel>
    </AVideTypeOptionnel>
    <AVideListeDeclarationVar>
    </AVideListeDeclarationVar>
    <AVideListeDeclarationVar>
    </AVideListeDeclarationVar>
    <ABlocInstruction>
     <AListeInstruction>
      <AAffectationInstruction>
       <ATableauVar>
        <AExp1Exp>
         <AExp2Exp1>
          <AExp3Exp2>
           <AExp4Exp3>
            <AExp5Exp4>
             <AExp6Exp5>
              <AExp7Exp6>
               <ANombreExp7>
               </ANombreExp7>
              </AExp7Exp6>
             </AExp6Exp5>
            </AExp5Exp4>
           </AExp4Exp3>
          </AExp3Exp2>
         </AExp2Exp1>
        </AExp1Exp>
       </ATableauVar>
       <AExp1Exp>
        <AExp2Exp1>
         <AExp3Exp2>
          <AExp4Exp3>
           <AExp5Exp4>
            <AExp6Exp5>
             <AExp7Exp6>
              <ANombreExp7>
              </ANombreExp7>
             </AExp7Exp6>
            </AExp6Exp5>
           </AExp5Exp4>
          </AExp4Exp3>
         </AExp3Exp2>
        </AExp2Exp1>
       </AExp1Exp>
      </AAffectationInstruction>
      <AListeInstruction>
       <AAffectationInstruction>
        <ATableauVar>
         <AExp1Exp>
          <AExp2Exp1>
           <AExp3Exp2>
            <AExp4Exp3>
             <AExp5Exp4>
              <AExp6Exp5>
               <AExp7Exp6>
                <ANombreExp7>
                </ANombreExp7>
               </AExp7Exp6>
              </AExp6Exp5>
             </AExp5Exp4>
            </AExp4Exp3>
           </AExp3Exp2>
          </AExp2Exp1>
         </AExp1Exp>
        </ATableauVar>
        <AExp1Exp>
         <AExp2Exp1>
          <AExp3Exp2>
           <AExp4Exp3>
            <AExp5Exp4>
             <AExp6Exp5>
              <AExp7Exp6>
               <ANombreExp7>
               </ANombreExp7>
              </AExp7Exp6>
             </AExp6Exp5>
            </AExp5Exp4>
           </AExp4Exp3>
          </AExp3Exp2>
         </AExp2Exp1>
        </AExp1Exp>
       </AAffectationInstruction>
       <AListeInstruction>
        <AAffectationInstruction>
         <ATableauVar>
          <AExp1Exp>
           <AExp2Exp1>
            <AExp3Exp2>
             <AExp4Exp3>
              <AExp5Exp4>
               <AExp6Exp5>
                <AExp7Exp6>
                 <ANombreExp7>
                 </ANombreExp7>
                </AExp7Exp6>
               </AExp6Exp5>
              </AExp5Exp4>
             </AExp4Exp3>
            </AExp3Exp2>
           </AExp2Exp1>
          </AExp1Exp>
         </ATableauVar>
         <AExp1Exp>
          <AExp2Exp1>
           <AExp3Exp2>
            <AExp4Exp3>
             <AExp5Exp4>
              <AExp6Exp5>
               <AExp7Exp6>
                <ANombreExp7>
                </ANombreExp7>
               </AExp7Exp6>
              </AExp6Exp5>
             </AExp5Exp4>
            </AExp4Exp3>
           </AExp3Exp2>
          </AExp2Exp1>
         </AExp1Exp>
        </AAffectationInstruction>
        <AListeInstruction>
         <AIncrInstruction>
          <ATableauVar>
           <AExp1Exp>
            <AExp2Exp1>
             <AExp3Exp2>
              <AExp4Exp3>
               <AExp5Exp4>
                <AExp6Exp5>
                 <AExp7Exp6>
                  <ANombreExp7>
                  </ANombreExp7>
                 </AExp7Exp6>
                </AExp6Exp5>
               </AExp5Exp4>
              </AExp4Exp3>
             </AExp3Exp2>
            </AExp2Exp1>
           </AExp1Exp>
          </ATableauVar>
          <AExp1Exp>
           <AExp2Exp1>
            <AExp3Exp2>
             <AExp4Exp3>
              <AMultExp4>
               <AExp5Exp4>
                <AExp6Exp5>
                 <AExp7Exp6>
                  <AVariableExp7>
                   <ATableauVar>
                    <AExp1Exp>
                     <AExp2Exp1>
                      <AExp3Exp2>
                       <AExp4Exp3>
                        <AExp5Exp4>
                         <AExp6Exp5>
                          <AExp7Exp6>
                           <ANombreExp7>
                           </ANombreExp7>
                          </AExp7Exp6>
                         </AExp6Exp5>
                        </AExp5Exp4>
                       </AExp4Exp3>
                      </AExp3Exp2>
                     </AExp2Exp1>
                    </AExp1Exp>
                   </ATableauVar>
                  </AVariableExp7>
                 </AExp7Exp6>
                </AExp6Exp5>
               </AExp5Exp4>
               <AExp6Exp5>
                <AExp7Exp6>
                 <AVariableExp7>
                  <ATableauVar>
                   <AExp1Exp>
                    <AExp2Exp1>
                     <AExp3Exp2>
                      <AExp4Exp3>
                       <AExp5Exp4>
                        <AExp6Exp5>
                         <AExp7Exp6>
                          <ANombreExp7>
                          </ANombreExp7>
                         </AExp7Exp6>
                        </AExp6Exp5>
                       </AExp5Exp4>
                      </AExp4Exp3>
                     </AExp3Exp2>
                    </AExp2Exp1>
                   </AExp1Exp>
                  </ATableauVar>
                 </AVariableExp7>
                </AExp7Exp6>
               </AExp6Exp5>
              </AMultExp4>
             </AExp4Exp3>
            </AExp3Exp2>
           </AExp2Exp1>
          </AExp1Exp>
         </AIncrInstruction>
         <AListeInstruction>
          <AEcrireInstruction>
           <AExp1Exp>
            <AExp2Exp1>
             <AExp3Exp2>
              <AExp4Exp3>
               <AExp5Exp4>
                <AExp6Exp5>
                 <AExp7Exp6>
                  <AVariableExp7>
                   <ATableauVar>
                    <AExp1Exp>
                     <AExp2Exp1>
                      <AExp3Exp2>
                       <AExp4Exp3>
                        <AExp5Exp4>
                         <AExp6Exp5>
                          <AExp7Exp6>
                           <ANombreExp7>
                           </ANombreExp7>
                          </AExp7Exp6>
                         </AExp6Exp5>
                        </AExp5Exp4>
                       </AExp4Exp3>
                      </AExp3Exp2>
                     </AExp2Exp1>
                    </AExp1Exp>
                   </ATableauVar>
                  </AVariableExp7>
                 </AExp7Exp6>
                </AExp6Exp5>
               </AExp5Exp4>
              </AExp4Exp3>
             </AExp3Exp2>
            </AExp2Exp1>
           </AExp1Exp>
          </AEcrireInstruction>
          <AVideListeInstruction>
          </AVideListeInstruction>
         </AListeInstruction>
        </AListeInstruction>
       </AListeInstruction>
      </AListeInstruction>
     </AListeInstruction>
    </ABlocInstruction>
   </ADeclarationFonc>
   <AVideListeDeclarationFonc>
   </AVideListeDeclarationFonc>
  </AListeDeclarationFonc>
 </AProgramme>
</Start>
