<Start>
 <AProgramme>
  <AListeDeclarationVar>
   <ADeclarationVar>
    <AEntierType>
    </AEntierType>
   </ADeclarationVar>
   <AListeDeclarationVarPrime>
    <ADeclarationVar>
     <AEntierType>
     </AEntierType>
    </ADeclarationVar>
    <AVideListeDeclarationVarPrime>
    </AVideListeDeclarationVarPrime>
   </AListeDeclarationVarPrime>
  </AListeDeclarationVar>
  <AListeDeclarationFonc>
   <ADeclarationFonc>
    <AVideTypeOptionnel>
    </AVideTypeOptionnel>
    <AVideListeDeclarationVar>
    </AVideListeDeclarationVar>
    <AVideListeDeclarationVar>
    </AVideListeDeclarationVar>
    <ABlocInstruction>
     <AListeInstruction>
      <AAffectationInstruction>
       <AVar>
       </AVar>
       <AExp1Exp>
        <AExp2Exp1>
         <AExp3Exp2>
          <AExp4Exp3>
           <AExp5Exp4>
            <AExp6Exp5>
             <AExp7Exp6>
              <ANombreExp7>
              </ANombreExp7>
             </AExp7Exp6>
            </AExp6Exp5>
           </AExp5Exp4>
          </AExp4Exp3>
         </AExp3Exp2>
        </AExp2Exp1>
       </AExp1Exp>
      </AAffectationInstruction>
      <AListeInstruction>
       <AAffectationInstruction>
        <AVar>
        </AVar>
        <AExp1Exp>
         <AExp2Exp1>
          <AExp3Exp2>
           <AExp4Exp3>
            <AExp5Exp4>
             <AExp6Exp5>
              <AExp7Exp6>
               <ANombreExp7>
               </ANombreExp7>
              </AExp7Exp6>
             </AExp6Exp5>
            </AExp5Exp4>
           </AExp4Exp3>
          </AExp3Exp2>
         </AExp2Exp1>
        </AExp1Exp>
       </AAffectationInstruction>
       <AListeInstruction>
        <AEcrireInstruction>
         <AExp1Exp>
          <AExp2Exp1>
           <AExp3Exp2>
            <AExp4Exp3>
             <AModuloExp4>
              <AExp5Exp4>
               <AExp6Exp5>
                <AExp7Exp6>
                 <AVariableExp7>
                  <AVar>
                  </AVar>
                 </AVariableExp7>
                </AExp7Exp6>
               </AExp6Exp5>
              </AExp5Exp4>
              <AExp6Exp5>
               <AExp7Exp6>
                <AVariableExp7>
                 <AVar>
                 </AVar>
                </AVariableExp7>
               </AExp7Exp6>
              </AExp6Exp5>
             </AModuloExp4>
            </AExp4Exp3>
           </AExp3Exp2>
          </AExp2Exp1>
         </AExp1Exp>
        </AEcrireInstruction>
        <AVideListeInstruction>
        </AVideListeInstruction>
       </AListeInstruction>
      </AListeInstruction>
     </AListeInstruction>
    </ABlocInstruction>
   </ADeclarationFonc>
   <AVideListeDeclarationFonc>
   </AVideListeDeclarationFonc>
  </AListeDeclarationFonc>
 </AProgramme>
</Start>
