<Start>
 <AProgramme>
  <AVideListeDeclarationVar>
  </AVideListeDeclarationVar>
  <AListeDeclarationFonc>
   <ADeclarationFonc>
    <ATypeTypeOptionnel>
     <AEntierType>
     </AEntierType>
    </ATypeTypeOptionnel>
    <AListeDeclarationVar>
     <ADeclarationVar>
      <AEntierType>
      </AEntierType>
     </ADeclarationVar>
     <AListeDeclarationVarPrime>
      <ADeclarationVar>
       <AEntierType>
       </AEntierType>
      </ADeclarationVar>
      <AVideListeDeclarationVarPrime>
      </AVideListeDeclarationVarPrime>
     </AListeDeclarationVarPrime>
    </AListeDeclarationVar>
    <AVideListeDeclarationVar>
    </AVideListeDeclarationVar>
    <ABlocInstruction>
     <AVideListeInstruction>
     </AVideListeInstruction>
    </ABlocInstruction>
   </ADeclarationFonc>
   <AListeDeclarationFonc>
    <ADeclarationFonc>
     <AVideTypeOptionnel>
     </AVideTypeOptionnel>
     <AVideListeDeclarationVar>
     </AVideListeDeclarationVar>
     <AVideListeDeclarationVar>
     </AVideListeDeclarationVar>
     <ABlocInstruction>
      <AListeInstruction>
       <AAppelFonctionInstruction>
        <AListeExp>
         <AExp1Exp>
          <AExp2Exp1>
           <AExp3Exp2>
            <AExp4Exp3>
             <AExp5Exp4>
              <AExp6Exp5>
               <AExp7Exp6>
                <ANombreExp7>
                </ANombreExp7>
               </AExp7Exp6>
              </AExp6Exp5>
             </AExp5Exp4>
            </AExp4Exp3>
           </AExp3Exp2>
          </AExp2Exp1>
         </AExp1Exp>
         <AVideListeExpPrime>
         </AVideListeExpPrime>
        </AListeExp>
       </AAppelFonctionInstruction>
       <AVideListeInstruction>
       </AVideListeInstruction>
      </AListeInstruction>
     </ABlocInstruction>
    </ADeclarationFonc>
    <AVideListeDeclarationFonc>
    </AVideListeDeclarationFonc>
   </AListeDeclarationFonc>
  </AListeDeclarationFonc>
 </AProgramme>
</Start>
