<Start>
 <AProgramme>
  <AVideListeDeclarationVar>
  </AVideListeDeclarationVar>
  <AListeDeclarationFonc>
   <ADeclarationFonc>
    <AVideTypeOptionnel>
    </AVideTypeOptionnel>
    <AVideListeDeclarationVar>
    </AVideListeDeclarationVar>
    <AVideListeDeclarationVar>
    </AVideListeDeclarationVar>
    <ABlocInstruction>
     <AListeInstruction>
      <AEcrireInstruction>
       <AExp1Exp>
        <AExp2Exp1>
         <AExp3Exp2>
          <AExp4Exp3>
           <AExp5Exp4>
            <AExp6Exp5>
             <AExp7Exp6>
              <ANombreExp7>
              </ANombreExp7>
             </AExp7Exp6>
            </AExp6Exp5>
           </AExp5Exp4>
          </AExp4Exp3>
         </AExp3Exp2>
        </AExp2Exp1>
       </AExp1Exp>
      </AEcrireInstruction>
      <AVideListeInstruction>
      </AVideListeInstruction>
     </AListeInstruction>
    </ABlocInstruction>
   </ADeclarationFonc>
   <AListeDeclarationFonc>
    <ADeclarationFonc>
     <AVideTypeOptionnel>
     </AVideTypeOptionnel>
     <AVideListeDeclarationVar>
     </AVideListeDeclarationVar>
     <AVideListeDeclarationVar>
     </AVideListeDeclarationVar>
     <ABlocInstruction>
      <AListeInstruction>
       <AAppelFonctionInstruction>
        <AVideListeExp>
        </AVideListeExp>
       </AAppelFonctionInstruction>
       <AVideListeInstruction>
       </AVideListeInstruction>
      </AListeInstruction>
     </ABlocInstruction>
    </ADeclarationFonc>
    <AVideListeDeclarationFonc>
    </AVideListeDeclarationFonc>
   </AListeDeclarationFonc>
  </AListeDeclarationFonc>
 </AProgramme>
</Start>
