<Start>
 <AProgramme>
  <AVideListeDeclarationVar>
  </AVideListeDeclarationVar>
  <AListeDeclarationFonc>
   <ADeclarationFonc>
    <AVideTypeOptionnel>
    </AVideTypeOptionnel>
    <AVideListeDeclarationVar>
    </AVideListeDeclarationVar>
    <AVideListeDeclarationVar>
    </AVideListeDeclarationVar>
    <ABlocInstruction>
     <AListeInstruction>
      <AEcrireInstruction>
       <AOuExp>
        <AExp1Exp>
         <AExp2Exp1>
          <AExp3Exp2>
           <AExp4Exp3>
            <AExp5Exp4>
             <AExp6Exp5>
              <AExp7Exp6>
               <AVraiExp7>
               </AVraiExp7>
              </AExp7Exp6>
             </AExp6Exp5>
            </AExp5Exp4>
           </AExp4Exp3>
          </AExp3Exp2>
         </AExp2Exp1>
        </AExp1Exp>
        <AExp2Exp1>
         <AExp3Exp2>
          <AExp4Exp3>
           <AExp5Exp4>
            <AExp6Exp5>
             <AExp7Exp6>
              <AVraiExp7>
              </AVraiExp7>
             </AExp7Exp6>
            </AExp6Exp5>
           </AExp5Exp4>
          </AExp4Exp3>
         </AExp3Exp2>
        </AExp2Exp1>
       </AOuExp>
      </AEcrireInstruction>
      <AVideListeInstruction>
      </AVideListeInstruction>
     </AListeInstruction>
    </ABlocInstruction>
   </ADeclarationFonc>
   <AVideListeDeclarationFonc>
   </AVideListeDeclarationFonc>
  </AListeDeclarationFonc>
 </AProgramme>
</Start>
